# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [81]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [82]:
print(np.__version__)
print(np.show_config())

2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.30
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/opt/miniconda3/conda-bld/numpy_and_

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [83]:
a = np.random.random((2,3,5))


### 4. Print a.


In [84]:
print(a)


[[[0.16389181 0.12787489 0.80785635 0.15604991 0.15417727]
  [0.69937852 0.79435512 0.47839596 0.80257823 0.34165685]
  [0.12041272 0.37356401 0.51696145 0.43501756 0.22858998]]

 [[0.12839713 0.07704933 0.10101902 0.10838853 0.63445046]
  [0.26730886 0.29241674 0.20093555 0.74774068 0.85465016]
  [0.94943178 0.73353751 0.72203876 0.22359463 0.90242859]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [85]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [86]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [87]:
print("Same size:", a.size == b.size)

Same size: True



### 8. Are you able to add a and b? Why or why not?


In [88]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
#No, because their shapes are incomopatible for broadcasting


Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [89]:
c = b.transpose(1, 2, 0)
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [90]:
d = a + c
print(d)
# The addition works because a and c have the same shape, so we can perform element-wise addition in NumPy.

[[[1.16389181 1.12787489 1.80785635 1.15604991 1.15417727]
  [1.69937852 1.79435512 1.47839596 1.80257823 1.34165685]
  [1.12041272 1.37356401 1.51696145 1.43501756 1.22858998]]

 [[1.12839713 1.07704933 1.10101902 1.10838853 1.63445046]
  [1.26730886 1.29241674 1.20093555 1.74774068 1.85465016]
  [1.94943178 1.73353751 1.72203876 1.22359463 1.90242859]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)
# d is equal to a + 1 because c is an array of ones. Since all elements in c are 1, adding c to a increases every value in a by exactly 1.


[[[0.16389181 0.12787489 0.80785635 0.15604991 0.15417727]
  [0.69937852 0.79435512 0.47839596 0.80257823 0.34165685]
  [0.12041272 0.37356401 0.51696145 0.43501756 0.22858998]]

 [[0.12839713 0.07704933 0.10101902 0.10838853 0.63445046]
  [0.26730886 0.29241674 0.20093555 0.74774068 0.85465016]
  [0.94943178 0.73353751 0.72203876 0.22359463 0.90242859]]]
[[[1.16389181 1.12787489 1.80785635 1.15604991 1.15417727]
  [1.69937852 1.79435512 1.47839596 1.80257823 1.34165685]
  [1.12041272 1.37356401 1.51696145 1.43501756 1.22858998]]

 [[1.12839713 1.07704933 1.10101902 1.10838853 1.63445046]
  [1.26730886 1.29241674 1.20093555 1.74774068 1.85465016]
  [1.94943178 1.73353751 1.72203876 1.22359463 1.90242859]]]



### 12. Multiply a and c. Assign the result to e.


In [100]:
e = a * c



### 13. Does e equal to a? Why or why not?


In [ ]:
print(np.array_equal(a, e))
#Yes, e is equal to a because c is an array of ones. Multiplying any value by 1 does not change it, so all elements in a remain the same in e.

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [94]:
### [your code here]

d_max = d.max()
d_min = d.min()
d_mean = d.mean()


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [95]:
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [102]:
d_min = d.min()
d_mean = d.mean()
d_max = d.max()

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i][j][k]

            if val == d_min:
                f[i][j][k] = 0
            elif val == d_max:
                f[i][j][k] = 100
            elif val == d_mean:
                f[i][j][k] = 50
            elif d_min < val < d_mean:
                f[i][j][k] = 25
            else:
                f[i][j][k] = 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [97]:
print(d)

[[[1.16389181 1.12787489 1.80785635 1.15604991 1.15417727]
  [1.69937852 1.79435512 1.47839596 1.80257823 1.34165685]
  [1.12041272 1.37356401 1.51696145 1.43501756 1.22858998]]

 [[1.12839713 1.07704933 1.10101902 1.10838853 1.63445046]
  [1.26730886 1.29241674 1.20093555 1.74774068 1.85465016]
  [1.94943178 1.73353751 1.72203876 1.22359463 1.90242859]]]


In [98]:
print(f)

[[[ 25.  25.  75.  25.  25.]
  [ 75.  75.  75.  75.  25.]
  [ 25.  25.  75.  25.  25.]]

 [[ 25.   0.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [100.  75.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [104]:
g = np.empty(d.shape, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i][j][k]

            if val == d_min:
                g[i][j][k] = "A"
            elif d_min < val < d_mean:
                g[i][j][k] = "B"
            elif val == d_mean:
                g[i][j][k] = "C"
            elif d_mean < val < d_max:
                g[i][j][k] = "D"
            else:
                g[i][j][k] = "E"
print(g)

[[['B' 'B' 'D' 'B' 'B']
  ['D' 'D' 'D' 'D' 'B']
  ['B' 'B' 'D' 'B' 'B']]

 [['B' 'A' 'B' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['E' 'D' 'D' 'B' 'D']]]
